title: ТСЖ «Вымпел»
description: Официальный сайт товарищества в Ульяновске
email: inbox@vympel73.ru
baseurl: ""
url: "https://vympel73.ru"
lang: ru

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Sass settings
sass:
    style: :compressed

analytics:
  google:
    tracking_code: UNKNOWN
  yandex:
    tracking_code: UNKNOWN

contacts:
  address: г. Ульяновск, ул. Островского, 23
  leader: Борисов Николай Иванович
  work_phone: 78422465032
  personal_phone: 79023565368
  email: inbox@vympel73.ru
  webmaster_email: inbox@gongled.ru
  github_url: https://github.com/gongled/vympel

paginate: 5
paginate_path: "/article/page:num/"

# Collections
collections:
  pages:
    output: true
    permalink: :path

# Defaults
defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: /article/:year/:month/:day/:title.html
  - scope:
      type: pages
    values:
      layout: page
